name: CD
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Lint and publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: bahmutov/npm-install@v1

      - name: Lint
        run: yarn lint

      - name: Deploy to NPM
        run: yarn semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_SEMANTIC_RELEASE }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
